version: '3.9'

services:
  elasticsearch:
    image: elasticsearch:8.6.0
    ports:
      - "9202:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    # healthcheck:
    #   test: ["CMD-SHELL", "curl --silent --fail localhost:9202/_cluster/health || exit 1"]
    #   interval: 5s
    #   timeout: 5s

  kibana:
    image: kibana:8.6.0
    ports:
      - "5602:5601"
    depends_on:
      - elasticsearch
        # condition: service_healthy

  logstash:
    image: logstash:8.6.0
    ports:
      - "5000:5000"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /home/troot/system/be/osint-v2/docker/scheduler/data/logs:/usr/share/logstash/scheduler/logs
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
        # condition: service_healthy